# Generated by Django 5.1.3 on 2024-11-18 04:33

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='original_image',
            field=models.ImageField(default='a', upload_to=diary.models.get_random_filename),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(upload_to=diary.models.get_random_filename),
        ),
    ]
